# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: your_postgres_database_username
          POSTGRES_PASSWORD: your_postgres_database_password
          POSTGRES_DB: ku_polls

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
        echo "DB_PORT=5432" >> $GITHUB_ENV

    - name: Run tests with coverage
      env:
        SECRET_KEY: secret-key-value-without-quotes
        DEBUG: false
        ALLOWED_HOSTS: localhost, 127.0.0.1, ::1, testserver
        TIME_ZONE: Asia/Bangkok
        POSTGRES_DB: ku_polls
        DB_USER: your_postgres_database_username
        DB_PWD: your_postgres_database_password
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
      run: |
        coverage run --source='.' manage.py test

    - name: Generate coverage report
      run: |
        coverage report
