name: Django + Selenium UI Tests

on: [push, pull_request]

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repo
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🌐 Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: 📤 Start Django server in background
      run: |
        python manage.py migrate
        nohup python manage.py runserver 0.0.0.0:8000 &
        sleep 10  # wait for the server to start

    - name: 🧪 Run Selenium UI tests
      run: |
        python polls/selenium_vote_test.py
